name: "BasicMinestomServer Maven CI"

on:
  push:
    branches:
      - "master"
  workflow_dispatch: {}

jobs:
  release:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
        with:
          submodules: "recursive"

      - name: "Set up JDK 21"
        uses: "actions/setup-java@v3"
        with:
          java-version: 21
          distribution: "corretto"
          cache: "gradle"

      - name: "Apply patches"
        run: "./gradlew applyPatches"

      - name: "Compiling BasicMinestomServer"
        run: "./gradlew build --no-daemon"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Latest Build"
          files: |
            LICENCE.txt
            build/libs/*.jar
